
# respaldo de los archivos de entrada y salida

a:\e_s\ipuertos.asm: ..\e_s\ipuertos.asm
	copy 	..\e_s\ipuertos.asm $*.asm

a:\e_s\recepcio.c: ..\e_s\recepcio.c
	copy ..\e_s\recepcio.c $*.c

a:\e_s\stdio.asm:  ..\e_s\stdio.asm
	copy ..\e_s\stdio.asm $*.asm

a:\e_s\saltoses.asm: ..\e_s\saltoses.asm
	copy ..\e_s\saltoses.asm $*.asm

a:\e_s\stdio.lib:  ..\e_s\stdio.lib
	copy ..\e_s\stdio.lib $*.lib
# fin del respaldo
