# respaldo de los archivos de respaldo make


a:\e_s\PRUEBA.MAK:  ..\e_s\PRUEBA.MAK
	copy ..\e_s\PRUEBA.MAK $*.mak

a:\e_s\COMAND.MAK: ..\e_s\COMAND.MAK
	copy ..\e_s\COMAND.MAK $*.mak

a:\e_s\RESPALS_.MAK: ..\e_s\RESPALS_.MAK
	copy ..\e_s\RESPALS_.MAK $*.mak

a:\e_s\INCLUYE.MAK: ..\e_s\INCLUYE.MAK
	copy ..\e_s\INCLUYE.MAK $*.mak

a:\e_s\E_S.MAK: ..\e_s\E_S.MAK
	copy ..\e_s\E_S.MAK  $*.mak

a:\e_s\remak.mak: ..\e_s\remak.mak
	copy ..\e_s\remak.mak $*.mak